name: Verify Recent Analysis
description: 'Verify that the most recent analysis is passing'
inputs:
  org:
    description: 'The organization to check'
    required: true
    default: ${{ github.repository_owner }}
  repo:
    description: 'The repository to check'
    required: true
    default: ${{ github.event.repository.name }}
  issue:
    description: 'The issue to comment on'
    required: true
    default: ${{ github.event.issue.number }}
  token:
    description: 'The token to use for authentication'
    required: true
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'